language: objective-c
osx_image: xcode9.1
env:
  global: 
script:
- xcodebuild -version
- xcodebuild -showsdks
- fastlane build
notifications:
  slack:
    secure: oAZp7O5Af12WZVuSl+BukxQJBhJ9D+B/SNcyk506jo/Gjz5WXKRD5x9WpX8f2W5k+AftiO+ecMbEytAwiqZIgviPfkpkY/VJtyjpq+n5OrzB6myY0NanmPRtfV7xBtrq8IbOPIdJ+ZrP68waUEpMse9e3lMfHGviXGHUc3bT6Iss9EA058V3LMsDrMf67ImPrcZGte4exssP8ib56fLbYwVt8mB/fPa/FODwv41h11JxSuNhNLK59QG0NQ7f7A99CoNmHF6eKvHtPgu8ICKNn6+41ET31UvhjYdGYKesnrJOni+G4nbhafzsbC6iKtfRYAxeS2utk7qmYwWbKON7UnFbhJ9gAwJLzAV6osjIUP7oIcExxgvfF+61qYRLlmH0R50rxYJslJd2tPcPpcC3IexrfcMbM1cPqmg03HHS8bXMBTHwaT1wMiEvl2HQBXWqvp8iP0B1KiI1y8mKl97/HTtYJUky0/ezHsP+P8iC+bmbgk649MkQJTpFMWEuZRrsow2xS7gNdiVz1PwfcDgXuta9qOcPIt96Cp5FsDRZKjleUJZGa5OcOSyDOqAADtPbX5879gA+zhsYoo9VlQ03M5FfulJEnyv5n1+Wz/wN1BmnBx9PlYe2Fzrs0Mb8DGNxNfGQWqhKrkYA8jEwB6pH5eNY7cVeJ70vM1Z+wbGpPms=
